[build]
  base = "frontend/"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "https://shakes-travel-backend.netlify.app/api"

# Netlify Identity configuration
[identity]
  settings = true
  # Enable external providers
  [identity.providers]
    # Google OAuth
    google = true
    # Email/password registration
    email = true
  [identity.external_providers]
    google = true
  # Registration settings  
  [identity.registration]
    # Allow open registration
    open = true
  # Email template settings
  [identity.emails]
    # Welcome email
    welcome = true
    # Email confirmation
    confirmation = true

# Automatic deployments configuration
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"
  
[context.branch-deploy]
  command = "npm run build"

# Deploy hooks for automatic builds
[build.processing]
  skip_processing = false

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

# Next.js rewrites and redirects
[[redirects]]
  from = "/api/*"
  to = "https://shakes-travel-backend.netlify.app/api/:splat"
  status = 200
  force = true

# Netlify Identity redirects
[[redirects]]
  from = "/auth/netlify-login"
  to = "/auth/netlify-login"
  status = 200

[[redirects]]
  from = "/auth/netlify-register"
  to = "/auth/netlify-register"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200