[build]
  base = "frontend/"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_API_URL = "https://shakestravel-backend.onrender.com"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  command = "npm run dev"
  port = 3000

# Next.js rewrites and redirects
[[redirects]]
  from = "/api/*"
  to = "https://shakestravel-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200