[phases.build]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PORT = "8080"