name = "shakestravel-api"
main = "src/index.ts"
compatibility_date = "2024-08-21"
workers_dev = false

# Production environment
[env.production]
name = "shakestravel-api-production"
workers_dev = false

# Custom domain route for API (will be configured after domain setup)
# [[env.production.routes]]
# pattern = "api.shakestravel.com/*"

# Staging environment
[env.staging]
name = "shakestravel-api-staging"
workers_dev = true

# Database bindings (D1)
[[env.production.d1_databases]]
binding = "DB"
database_name = "shakestravel-production"
database_id = "9f783a6c-0a3d-4f72-aecc-bca04dc8d524"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "shakestravel-staging"
database_id = "85ce4e70-01e2-46e9-bea5-23edb556bada"

# KV storage for sessions/cache
[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "6c66f5a100784d39b927355d0c45c8dc"
preview_id = "f033e05fc12d49d09533daa92f8d0bf4"

[[env.staging.kv_namespaces]]
binding = "SESSIONS"
id = "6c66f5a100784d39b927355d0c45c8dc"
preview_id = "f033e05fc12d49d09533daa92f8d0bf4"

# R2 storage for file uploads (enable R2 in dashboard first)
# [[env.production.r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "shakestravel-uploads"

# [[env.staging.r2_buckets]]
# binding = "UPLOADS"
# bucket_name = "shakestravel-uploads-staging"

# Variables (set via wrangler secret put)
[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"

# Secrets to set via CLI:
# wrangler secret put JWT_SECRET
# wrangler secret put JWT_REFRESH_SECRET  
# wrangler secret put STRIPE_SECRET_KEY
# wrangler secret put STRIPE_WEBHOOK_SECRET
# wrangler secret put CLOUDINARY_API_KEY
# wrangler secret put CLOUDINARY_API_SECRET
# wrangler secret put RESEND_API_KEY